trigger:
- main

pool: "Mac"


steps:

- script: |

    npm install
    npm run build
  displayName: "Build"

- task: SonarCloudPrepare@3
  inputs:
    SonarQube: 'SonarCloud'
    organization: 'tolgahanakca'
    scannerMode: 'dotnet'
    projectKey: '8346dd878d3338f208ee181f58dff50efe5c7bae'
    projectName: 'tolgahanakca_probuddy'

- task: SonarCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'




  





